### ISSUE TITLE
checking for ranged classes

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/MultiOmicQC#1]
Is it safe to assume that all incoming classes have a `rowRanges` method or should there be a more formal way to test range-type classes?
For now, the code just checks ranged class membership such as `RangedSummarizedExperiment` and `RaggedExperiment`. This is not ideal and should allow extensibility.
https://github.com/Bioconductor/MultiOmicQC/blob/dev/R/checkSeqlevels.R#L1

**Note**. Since these functions will be working on a `MultiAssayExperiment`, we assume that they conform to the basic API requirements (`dim`, `dimnames`, `[`).

**Comment by lwaldron** [comment]
Since this is operating on the entire `MultiAssayExperiment`, I don't think you can in general assume that all objects have a `rowRanges` method, and this requirement isn't in the API. Could you define something like an `isRanged()` method for `MultiAssayExperiment` and `ExperimentList` that returns a logical with `TRUE` for each element where `rowRanges` returns a `GRanges` object? Then you could use this to subset the `MultiAssayExperiment` before checking its remaining elements.

**Comment by LiNk-NY** [comment]
Hi Levi, @lwaldron 
Thanks for the guidance. I added a method called `hasRowRanges` to `MultiAssayExperiment` and `ExperimentList` for this.
I went with this name because we're specifically checking for `rowRanges` support.
See https://github.com/waldronlab/MultiAssayExperiment/commit/6788a67dcdc8abcd3f812b22522328809698718a
